name: CD

on:
  push:
    branches: [ deploy ] # deploy branch로 push 될 때 실행됩니다.

env:
  S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
  PROJECT_NAME: poppin-be
  
jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Print current working directory
        run: ls -lR
      
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
        working-directory: ./
        
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
        env:
          GITHUB_SHA: ${{ github.sha }}
          
      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name codedeploy \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name cicd-prod \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip \
          --region ap-northeast-2
          
